/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_jdk1_6_24/jni.h"
/* Header for class org_fastipc_FastIPCNative */

#ifndef _Included_org_fastipc_FastIPCNative
#define _Included_org_fastipc_FastIPCNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fastipc_FastIPCNative_nExit
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_a_A_a
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
