/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fastipc_FastIPCNative */

#ifndef _Included_org_fastipc_FastIPCNative
#define _Included_org_fastipc_FastIPCNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    data
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_fastipc_FastIPCNative_data
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    OnRead
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_fastipc_FastIPCNative_OnRead
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nCreateServer
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_fastipc_FastIPCNative_nCreateServer
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nStartRead
 * Signature: (ILorg/fastipc/FastIPCReadListener;)V
 */
JNIEXPORT void JNICALL Java_org_fastipc_FastIPCNative_nStartRead
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nCloseServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_fastipc_FastIPCNative_nCloseServer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nCreateClient
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_fastipc_FastIPCNative_nCreateClient
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_fastipc_FastIPCNative
 * Method:    nWriteClient
 * Signature: (ILorg/fastipc/FastIPCData;)I
 */
JNIEXPORT jint JNICALL Java_org_fastipc_FastIPCNative_nWriteClient
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
